#!/usr/bin/env python3
"""
Retailer Composer

Reads a capability profile JSON and/or Ad Type Hint Pack YAML and scaffolds 
a production-ready retailer adapter. Enforces canonical schema, brand lexicon, 
and path taxonomy.

Hint Pack takes priority over profiler heuristics.
"""
import json, os, sys, shutil, yaml
from pathlib import Path
from datetime import datetime

PROJECT = Path(__file__).resolve().parents[1]

RULES = {
    "kroger_like": lambda caps: caps["requires_auth"] or caps["persistent_profile_required"],
    "walmart_like": lambda caps: caps["anti_bot_vendor"] in ("perimeterx","akamai","cloudflare") or not caps["headless_allowed"],
    "instacart_like": lambda caps: caps["has_lazy_loading"] or caps["hashed_class_density"] in ("high","medium"),
}

ADTYPE_MAP = {
    "CuratedCarousel": "Carousel",
    "TOA": "TOA",
    "Skyscraper": "Skyscraper",
    "SBA": "SBA",
    "SBV": "SBV",
    "Tile_Takeover": "Tile_Takeover",
}

def load_hint_pack(hint_path: Path) -> dict:
    """Load Ad Type Hint Pack YAML"""
    if not hint_path.exists():
        return None
    return yaml.safe_load(hint_path.read_text())

def recommend(caps: dict, hint_pack: dict = None) -> dict:
    """Analyze capabilities and recommend code patterns
    
    Hint pack takes priority over profiler heuristics.
    """
    # If hint pack provided, use it as source of truth
    if hint_pack:
        pick = {
            "use_kroger_profile": hint_pack.get("requires_auth", False),
            "use_walmart_nav": hint_pack.get("anti_bot_hint", {}).get("vendor") in ("perimeterx", "akamai", "cloudflare"),
            "use_instacart_scroller": False,  # Can be inferred from notes
            "adtypes": [ad["canonical"] for ad in hint_pack.get("ad_types", [])],
            "hint_pack": hint_pack,  # Pass through for detailed extraction
        }
        return pick
    
    # Fallback to profiler heuristics
    pick = {
        "use_kroger_profile": RULES["kroger_like"](caps),
        "use_walmart_nav": RULES["walmart_like"](caps),
        "use_instacart_scroller": RULES["instacart_like"](caps),
        "adtypes": [],
        "hint_pack": None,
    }
    hints = caps.get("ad_hints", {})
    if hints.get("curated_carousel_like"): pick["adtypes"].append("CuratedCarousel")
    if hints.get("toa_like"): pick["adtypes"].append("TOA")
    if hints.get("skyscraper_like"): pick["adtypes"].append("Skyscraper")
    if hints.get("sba_like"): pick["adtypes"].append("SBA")
    if hints.get("video_in_grid_like"): pick["adtypes"].append("SBV")
    if hints.get("tile_takeover_like"): pick["adtypes"].append("Tile_Takeover")
    pick["adtypes"] = sorted(set(pick["adtypes"]))
    return pick

def write_adapter(slug: str, caps: dict, pick: dict):
    """Generate adapter.py"""
    adapter_path = PROJECT / f"retailers/{slug}/adapter.py"
    
    adapter_code = f'''# retailers/{slug}/adapter.py
"""
{slug.title()} Retailer Adapter
Auto-generated by compose_retailer.py on {datetime.now().strftime("%Y-%m-%d")}
"""
from __future__ import annotations
import os, glob, time, subprocess
from datetime import datetime
from core.retailers import RetailerAdapter, register


class {slug.title().replace("-","").replace("_","")}Adapter(RetailerAdapter):
    slug = "{slug}"
    display_name = "{slug.title()}"
    profile_env = "{slug.upper()}_PROFILE_DIR"

    def search_and_capture(self, keyword: str, ctx) -> bool:
        """Execute {slug} search and capture HTML/JSON."""
        # Inject profile for session continuity (auth/CDN cookies)
        if ctx.profile_dir and os.path.isdir(ctx.profile_dir):
            os.environ[self.profile_env] = ctx.profile_dir
            print(f"Injected {{self.profile_env}} into env: {{ctx.profile_dir}}")
        
        import sys
        sys.path.insert(0, ctx.script_dir)
        from {slug}_search_and_capture import search_and_capture
        return search_and_capture(keyword, ctx.output_dir)

    def collect_pairs_for_run(self, ctx, run_start_ts: float):
        """Collect JSON/HTML pairs from the most recent run."""
        runs = os.path.join(ctx.output_dir, "runs")
        jsons = sorted([p for p in glob.glob(os.path.join(runs, "run_results_*.json"))
                        if os.path.getmtime(p) >= run_start_ts - 2], key=os.path.getmtime)
        pairs = []
        for j in jsons:
            html = j.replace("run_results_", "search_results_").replace(".json", ".html")
            if os.path.exists(html):
                pairs.append((j, html))
        return pairs

    def extract_images(self, json_path: str, html_path: str, ctx) -> dict:
        """Extract ad images using screenshot script."""
        script = os.path.join(ctx.script_dir, "extractors/screenshot_ad_images.py")
        cmd = [
            os.sys.executable, script,
            "--json", json_path,
            "--html", html_path,
            "--output", ctx.output_dir,
            "--headless",
            "--no-lock",
            "--time-window", "45",
            "--browser-lock-timeout", "600",
        ]
        
        env = os.environ.copy()
        if ctx.profile_dir and os.path.isdir(ctx.profile_dir):
            cmd += ["--profile-dir", ctx.profile_dir]
            env[self.profile_env] = ctx.profile_dir
        
        log_dir = ctx.logs_dir
        os.makedirs(log_dir, exist_ok=True)
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        log_path = os.path.join(log_dir, f"image_extract_{{ts}}.log")
        pair_start = time.time()
        
        with open(log_path, "w", encoding="utf-8") as lf:
            lf.write(f"=== START {{datetime.now().isoformat()}} ===\\n")
            lf.write(f"CMD: {{' '.join(cmd)}}\\nCWD: {{ctx.script_dir}}\\n\\n")
            proc = subprocess.Popen(
                cmd, env=env, cwd=ctx.script_dir,
                stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                text=True, encoding="utf-8", errors="replace", bufsize=1,
            )
            for line in iter(proc.stdout.readline, ""):
                lf.write(line)
            try:
                proc.wait(timeout=240)
            except subprocess.TimeoutExpired:
                proc.kill()
                lf.write("\\n❌ Timeout: 240s\\n")
            lf.write(f"Exit code: {{proc.returncode}}\\n")
            lf.write(f"=== END {{datetime.now().isoformat()}} ===\\n")
        
        def count(leaf: str) -> int:
            return len([p for p in glob.glob(os.path.join(ctx.output_dir, leaf, "*.png"))
                        if os.path.getmtime(p) >= pair_start - 1])
        
        return {{"toa": count("TOA"), "sky": count("Skyscraper"), "car": count("Carousel"), "log": log_path}}


# Register on import
register({slug.title().replace("-","").replace("_","")}Adapter())
'''
    
    adapter_path.parent.mkdir(parents=True, exist_ok=True)
    adapter_path.write_text(adapter_code)
    print(f"✅ Created {adapter_path}")

def write_search_script(slug: str, caps: dict, pick: dict):
    """Generate search_and_capture.py"""
    script_path = PROJECT / f"{slug}_search_and_capture.py"
    
    # Build search URL pattern
    base_url = caps["base_url"].rstrip("/")
    if caps["search_url_shape"] == "?q=":
        search_url_template = f'{base_url}/search?q={{keyword}}'
    elif caps["search_url_shape"] == "?query=":
        search_url_template = f'{base_url}/search?query={{keyword}}'
    else:
        search_url_template = f'{base_url}/search?q={{keyword}}'
    
    # Choose navigation strategy
    if pick["use_walmart_nav"]:
        nav_strategy = '''    # Organic search (bot avoidance)
    try:
        page.goto(base_url, wait_until="domcontentloaded", timeout=30000)
        page.wait_for_load_state("load")
        
        # Find and click search input
        search_input = page.locator("input[placeholder*='Search'], input[type='search']").first
        search_input.click()
        search_input.fill(keyword)
        page.keyboard.press("Enter")
        page.wait_for_load_state("domcontentloaded", timeout=30000)
        time.sleep(3)
    except Exception as e:
        print(f"⚠️ Organic search failed, falling back to direct URL: {e}")
        page.goto(search_url, wait_until="domcontentloaded", timeout=30000)
        time.sleep(3)'''
    else:
        nav_strategy = '''    # Direct navigation
    page.goto(search_url, wait_until="domcontentloaded", timeout=30000)
    time.sleep(3)'''
    
    # Choose scroll strategy
    if pick["use_instacart_scroller"]:
        scroll_code = '''    # Lazy-load scroll
    for _ in range(3):
        page.evaluate("window.scrollBy(0, window.innerHeight)")
        time.sleep(0.5)
    page.evaluate("window.scrollTo(0, 0)")
    time.sleep(1)'''
    else:
        scroll_code = '''    # Basic scroll
    page.evaluate("window.scrollBy(0, 1000)")
    time.sleep(0.5)'''
    
    script_code = f'''#!/usr/bin/env python3
"""
{slug.title()} Search and Capture
Auto-generated by compose_retailer.py on {datetime.now().strftime("%Y-%m-%d")}

Capabilities detected:
- Auth required: {caps["requires_auth"]}
- Anti-bot: {caps["anti_bot_vendor"]} ({caps["anti_bot_level"]})
- Headless allowed: {caps["headless_allowed"]}
- Lazy loading: {caps["has_lazy_loading"]}
"""
import os
import sys
import json
import time
from datetime import datetime, timezone
from pathlib import Path
from playwright.sync_api import sync_playwright, TimeoutError as PlaywrightTimeout

# Canonical helpers
from utils.time_utils import now_iso_z
from core.brands import canonicalize
from filename_utils import generate_ad_filename


def build_run_id() -> str:
    """Generate 14-digit run ID: YYYYMMDDHHMMSS (local time)"""
    return datetime.now().strftime("%Y%m%d%H%M%S")


def build_ad_object(run_id: str, index: int, ad_type: str, brand: str, 
                    image_path: str, **kwargs) -> dict:
    """Build a canonical ad object."""
    # Canonicalize brand
    canon_brand = canonicalize(brand) if brand else None
    
    return {{
        "id": f"{slug}-{{run_id}}-{{index}}",
        "type": ad_type,
        "brand": canon_brand or brand,
        "brand_logo": None,
        "title": kwargs.get("title"),
        "description": kwargs.get("description"),
        "cta": kwargs.get("cta"),
        "href": kwargs.get("href"),
        "image_url": kwargs.get("image_url"),
        "image_path": image_path,
        "products": kwargs.get("products", []),
        "metadata": {{
            "slot": kwargs.get("slot", 0),
            **kwargs.get("metadata", {{}})
        }}
    }}


def search_and_capture(keyword: str, output_dir: str, **kwargs) -> bool:
    """
    Search {slug} for a keyword and capture results.
    
    Args:
        keyword: Search term
        output_dir: Base output directory (e.g., output/{slug}/client_name)
        **kwargs: Additional parameters
    
    Returns:
        True if successful, False otherwise
    """
    # Get profile directory
    profile_dir = os.environ.get('{slug.upper()}_PROFILE_DIR')
    if not profile_dir or not os.path.isdir(profile_dir):
        print(f"❌ {slug.upper()}_PROFILE_DIR not set or invalid: {{profile_dir}}")
        print(f"Run: ./scripts/setup_{slug}_profile.sh")
        return False
    
    # Create runs directory
    runs_dir = os.path.join(output_dir, "runs")
    os.makedirs(runs_dir, exist_ok=True)
    
    # Generate run metadata
    run_id = build_run_id()
    timestamp = now_iso_z()
    run_ts = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    
    html_file = os.path.join(runs_dir, f"search_results_{{keyword}}_{{run_ts}}.html")
    json_file = os.path.join(runs_dir, f"run_results_{{run_id}}.json")
    
    print(f"🔍 Searching {slug.title()} for: '{{keyword}}'")
    print(f"   Profile: {{profile_dir}}")
    print(f"   Run ID: {{run_id}}")
    
    base_url = "{base_url}"
    search_url = f"{search_url_template}"
    
    ads_list = []
    
    try:
        with sync_playwright() as p:
            # Launch with persistent context (authenticated session)
            context = p.chromium.launch_persistent_context(
                user_data_dir=profile_dir,
                headless={"False" if not caps["headless_allowed"] else "True"},
                viewport={{'width': 1920, 'height': 1080}},
                locale='en-US',
            )
            
            page = context.pages[0] if context.pages else context.new_page()
            
            print(f"   URL: {{search_url}}")
            
{nav_strategy}
            
{scroll_code}
            
            # Get page content
            html_content = page.content()
            
            # Save HTML
            with open(html_file, 'w', encoding='utf-8') as f:
                f.write(html_content)
            print(f"💾 HTML saved: {{html_file}}")
            
            # TODO: Extract ads from page
            # For now, create placeholder ad objects
            # You'll need to add selectors specific to this retailer
            
            print(f"📊 Found {{len(ads_list)}} ad units")
            
            context.close()
            
            # Build canonical JSON
            canonical_json = {{
                "retailer": "{slug}",
                "client": os.path.basename(output_dir),
                "keyword": keyword,
                "timestamp": timestamp,
                "run_id": run_id,
                "ads": ads_list,
            }}
            
            # Save canonical JSON
            with open(json_file, 'w', encoding='utf-8') as f:
                json.dump(canonical_json, f, indent=2, ensure_ascii=False)
            print(f"💾 JSON saved: {{json_file}}")
            
            return True
            
    except PlaywrightTimeout as e:
        print(f"❌ Timeout: {{e}}")
        return False
    except Exception as e:
        print(f"❌ Error: {{e}}")
        import traceback
        traceback.print_exc()
        return False


if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser(description='Search {slug.title()} and capture results')
    parser.add_argument('keyword', help='Search keyword')
    parser.add_argument('--output-dir', required=True, help='Output directory')
    
    args = parser.parse_args()
    
    success = search_and_capture(args.keyword, args.output_dir)
    sys.exit(0 if success else 1)
'''
    
    script_path.write_text(script_code)
    script_path.chmod(0o755)
    print(f"✅ Created {script_path}")

def write_init(slug: str):
    """Generate __init__.py"""
    init_path = PROJECT / f"retailers/{slug}/__init__.py"
    class_name = slug.title().replace("-","").replace("_","")
    
    init_code = f'''from .adapter import {class_name}Adapter

__all__ = ['{class_name}Adapter']
'''
    
    init_path.write_text(init_code)
    print(f"✅ Created {init_path}")

def update_taxonomy(slug: str, adtypes: list):
    """Update utils/path_taxonomy.py"""
    taxonomy_path = PROJECT / "utils/path_taxonomy.py"
    
    if not taxonomy_path.exists():
        print(f"⚠️ {taxonomy_path} not found - skipping taxonomy update")
        return
    
    content = taxonomy_path.read_text()
    
    # Build folder set
    folders = set(ADTYPE_MAP.get(at, at) for at in adtypes)
    folders.add("Main")
    folders.add("runs")
    
    folders_str = ",\n        ".join(f'"{f}"' for f in sorted(folders))
    
    new_entry = f'''    "{slug}": {{
        {folders_str},
    }},'''
    
    # Insert before closing brace
    if f'"{slug}"' not in content:
        content = content.replace(
            "\n}",
            f"\n{new_entry}\n}}"
        )
        taxonomy_path.write_text(content)
        print(f"✅ Updated {taxonomy_path}")
    else:
        print(f"⚠️ {slug} already in taxonomy - skipping")

def update_keyword_input(slug: str):
    """Update keyword_input.py to import adapter"""
    keyword_input_path = PROJECT / "keyword_input.py"
    
    if not keyword_input_path.exists():
        print(f"⚠️ {keyword_input_path} not found - skipping")
        return
    
    content = keyword_input_path.read_text()
    import_line = f"import retailers.{slug}.adapter  # noqa: F401"
    
    if import_line not in content:
        # Find the adapter imports section
        if "import retailers." in content:
            lines = content.split("\n")
            for i, line in enumerate(lines):
                if "import retailers." in line and "# noqa: F401" in line:
                    lines.insert(i + 1, import_line)
                    break
            content = "\n".join(lines)
            keyword_input_path.write_text(content)
            print(f"✅ Updated {keyword_input_path}")
        else:
            print(f"⚠️ Could not find adapter import section in {keyword_input_path}")
    else:
        print(f"⚠️ {slug} adapter already imported - skipping")

def create_setup_script(slug: str, caps: dict):
    """Create setup script"""
    script_path = PROJECT / f"scripts/setup_{slug}_profile.sh"
    script_path.parent.mkdir(parents=True, exist_ok=True)
    
    script_code = f'''#!/bin/bash
# Setup {slug.title()} authentication profile

PROFILE_DIR=~/Documents/Amazon_Scrape/profiles/{slug}
mkdir -p "$PROFILE_DIR"

echo "🔐 Setting up {slug.title()} authentication profile..."
python3 auth/retailer_auth.py --retailer {slug} --profile-dir "$PROFILE_DIR"

echo ""
echo "✅ Profile created at: $PROFILE_DIR"
echo ""
echo "Add to ~/.zshrc or ~/.bash_profile:"
echo "export {slug.upper()}_PROFILE_DIR=$PROFILE_DIR"
echo ""
echo "Or add to config/launcher.env:"
echo "{slug.upper()}_PROFILE_DIR=$PROFILE_DIR"
'''
    
    script_path.write_text(script_code)
    script_path.chmod(0o755)
    print(f"✅ Created {script_path}")

def main():
    import argparse
    ap = argparse.ArgumentParser(description="Compose a retailer adapter from capability profile and/or hint pack")
    ap.add_argument("--profile", help="Path to capability profile JSON (optional if hint-pack provided)")
    ap.add_argument("--hint-pack", help="Path to Ad Type Hint Pack YAML (takes priority)")
    ap.add_argument("--slug", help="Retailer slug (overrides auto-detection)")
    args = ap.parse_args()
    
    if not args.profile and not args.hint_pack:
        print("❌ Must provide --profile and/or --hint-pack")
        sys.exit(1)
    
    # Load hint pack (priority)
    hint_pack = None
    if args.hint_pack:
        hint_path = Path(args.hint_pack)
        if not hint_path.exists():
            print(f"❌ Hint pack not found: {hint_path}")
            sys.exit(1)
        hint_pack = load_hint_pack(hint_path)
        print(f"📦 Loaded hint pack: {hint_path}")
    
    # Load profile (optional if hint pack provided)
    caps = {}
    if args.profile:
        profile_path = Path(args.profile)
        if not profile_path.exists():
            print(f"❌ Profile not found: {profile_path}")
            sys.exit(1)
        caps = json.loads(profile_path.read_text())
        print(f"📊 Loaded profile: {profile_path}")
    
    # Determine slug
    if args.slug:
        slug = args.slug
    elif hint_pack:
        slug = hint_pack.get("retailer", "unknown")
    elif caps:
        slug = caps.get("retailer_hint", "unknown").replace("www.", "").split(".")[0]
    else:
        print("❌ Could not determine retailer slug")
        sys.exit(1)
    
    print(f"\n🏗️  Composing retailer adapter for: {slug}")
    if hint_pack:
        print(f"   Source: Hint Pack (priority)")
    if caps:
        print(f"   Augmented by: Profiler")
    print()
    
    # Analyze and recommend (hint pack takes priority)
    pick = recommend(caps, hint_pack)
    
    print("📋 Recommendations:")
    print(f"   Use Kroger-like profile: {pick['use_kroger_profile']}")
    print(f"   Use Walmart-like navigation: {pick['use_walmart_nav']}")
    print(f"   Use Instacart-like scroller: {pick['use_instacart_scroller']}")
    print(f"   Ad types: {', '.join(pick['adtypes']) if pick['adtypes'] else 'None detected'}")
    print()
    
    # Generate files
    print("📝 Generating files...")
    write_adapter(slug, caps, pick)
    write_search_script(slug, caps, pick)
    write_init(slug)
    update_taxonomy(slug, pick["adtypes"])
    update_keyword_input(slug)
    create_setup_script(slug, caps)
    
    print()
    print("✅ Composition complete!")
    print()
    print("📌 Next steps:")
    print(f"   1. Run: ./scripts/setup_{slug}_profile.sh")
    print(f"   2. Add {slug.upper()}_PROFILE_DIR to config/launcher.env")
    print(f"   3. Update {slug}_search_and_capture.py with actual ad selectors")
    print(f"   4. Test: python3 {slug}_search_and_capture.py 'test' --output-dir output/{slug}/test")
    print(f"   5. Test in GUI: python3 keyword_input.py")
    print()

if __name__ == "__main__":
    main()
